### ISSUE TITLE
Not all umpire data is getting pushed to the realtime db

### ISSUE THREAD

**Issue by kravisankaran** [cricketclubucd/davisdragons#17]
<img width="1280" alt="screen shot 2017-09-10 at 8 01 04 pm" src="https://user-images.githubusercontent.com/13433292/30254209-f2c9d108-9662-11e7-8343-d32b92381608.png">

<img width="1280" alt="screen shot 2017-09-10 at 8 00 40 pm" src="https://user-images.githubusercontent.com/13433292/30254203-e07778b6-9662-11e7-8c72-3f89211e3a7c.png">

<img width="1280" alt="screen shot 2017-09-10 at 8 00 54 pm" src="https://user-images.githubusercontent.com/13433292/30254205-ee7330d6-9662-11e7-8faa-fda0eb82a8db.png">

The current code is able to recognize the first score input by the umpire and is able to accurately assign it to the db, however subsequent inputs arent getting pushed to the db.

The file in question is under src/pages/umpire/ directory

**Comment by skjena** [comment]
This method structure looks unorganized, let's go for a complete modularizing change.

**Comment by kravisankaran** [comment]
The issue is now fixed: 
If you are expecting a real time data inflow, you'd need to use FirebaseListObservable <> object to reference the database and push the data to that reference.
In reference to our code:
I declared this object above the constructor of the UmpirePage class
`data : FirebaseListObservable<any>;`
And inside the constructor, I set the reference to the balls field in our database using the "data" observable
`this. data = fdb.list('/balls');`  - (this will change based on which field you want to push your data under)
And I made this modification to the pushdata() that take care of pushing the data into the realtime db
`pushdata()
 {
   var data1= {
     runs : this.score
   }
   this.data.push(data1);
 }`
