### ISSUE TITLE
Customizable Key for each ball

### ISSUE THREAD

**Issue by kravisankaran** [cricketclubucd/davisdragons#18]
After scouring the internet for information on customizing the key generated by firebase for each ball for more than 2 hrs, I am yet to come up with a feasible solution. AngularFire has updated their latest methods, so the posts that are currently available are all with respect to old documentation.
Any help or suggestions would be highly appreciated

**Comment by skjena** [comment]
So are the keys auto configured?

**Comment by skjena** [comment]
As in does Firebase provide it's own key, and are we able to modify it? If we aren't then it's not too much of an issue

**Comment by kravisankaran** [comment]
Yes they are auto generated by firebase push. Cool thanks for confirming
